alias ins="sudo apt-get install"
alias c='clear'
alias h='history'
alias q='exit'
alias reboot='sudo /sbin/reboot'
alias poweroff='sudo /sbin/poweroff'
alias halt='sudo /sbin/halt'
alias shutdown='sudo /sbin/shutdown'
alias reload='source ~/.zshrc'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias gg='gitg &'
alias p='ping google.com'
export GOPATH=/home/muhzin/work/go-workspace
export PATH=$PATH:/usr/local/go/bin
